### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Nef1k** [Nef1k/CommandSystem#11]
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1967)
	at com.ns_team.commands_system.Parser.ParamParse(Parser.java:38)
	at com.ns_team.commands_system.Parser.parseCommand(Parser.java:14)
	at com.ns_team.commands_system.CommandManager.executeCommandString(CommandManager.java:29)
	at com.ns_team.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by Zzzkvidi4** [comment]
Да твою мать...

**Comment by Zzzkvidi4** [comment]
Оно же повыводит результаты перед тем, как столкнуться с исключением, правда?

**Comment by Nef1k** [comment]
"C:\Program Files\Java\jdk1.8.0_101\bin\java" -Didea.launcher.port=7532 -Didea.launcher.bin.path=M:\IDEs\IntelliJIDEA\bin -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_101\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\rt.jar;D:\Projects\Univer\CommandSystem\out\production\CommandSystem;M:\IDEs\IntelliJIDEA\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain com.ns_team.Main
pos = 9
cmd_text.indexOf(' ')8
cmd_text.length()44
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1967)
	at com.ns_team.commands_system.Parser.ParamParse(Parser.java:41)
	at com.ns_team.commands_system.Parser.parseCommand(Parser.java:14)
	at com.ns_team.commands_system.CommandManager.executeCommandString(CommandManager.java:29)
	at com.ns_team.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by Nef1k** [comment]
pos = 9
cmd_text.indexOf(' ')8
cmd_text.length()44
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1967)
	at com.ns_team.commands_system.Parser.ParamParse(Parser.java:41)
	at com.ns_team.commands_system.Parser.parseCommand(Parser.java:14)
	at com.ns_team.commands_system.CommandManager.executeCommandString(CommandManager.java:29)
	at com.ns_team.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Вот так лучше. Прошлое игнорь

**Comment by Zzzkvidi4** [comment]
А... Понял

**Comment by Nef1k** [comment]
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -10
	at java.lang.String.substring(String.java:1967)
	at com.ns_team.commands_system.Parser.ParamParse(Parser.java:42)
	at com.ns_team.commands_system.Parser.parseCommand(Parser.java:14)
	at com.ns_team.commands_system.CommandManager.executeCommandString(CommandManager.java:29)
	at com.ns_team.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
pos = 9
cmd_text.indexOf(' ')0
cmd_text.length()36

Process finished with exit code 1

**Comment by Nef1k** [comment]
Fixed
