### ISSUE TITLE
И ещё один StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Nef1k** [Nef1k/CommandSystem#14]
```java
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.ns_team.cmds.parsers.Parser.CmdIdParse(Parser.java:35)
	at com.ns_team.cmds.parsers.Parser.parseCommand(Parser.java:26)
	at com.ns_team.cmds.CommandManager.executeCommandString(CommandManager.java:33)
	at com.ns_team.cmds_demo.Main.main(Main.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by Nef1k** [comment]
```
    public static void main(String args[]){
        CommandManager commandManager = new CommandManager();

        commandManager.setDefaultCmd(new InvalidCommand());
        commandManager.registerCmd(new HelloCommand());

        commandManager.executeCommandString("hello", null);
    }
```
