### ISSUE TITLE
Another exception

### ISSUE THREAD

**Issue by Nef1k** [Nef1k/CommandSystem#2]
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1960)
	at com.ns_team.commands_system.Parser.parseCommand(Parser.java:29)
	at com.ns_team.commands_system.CommandManager.executeCommandString(CommandManager.java:44)
	at com.ns_team.Main.main(Main.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by Nef1k** [comment]
Fixed
