### ISSUE TITLE
Косяк при перегонке параметров из результата в команду

### ISSUE THREAD

**Issue by Nef1k** [Nef1k/CommandSystem#4]
Exception in thread "main" java.lang.NullPointerException
	at com.ns_team.commands_system.CommandManager.executeCommandString(CommandManager.java:50)
	at com.ns_team.Main.main(Main.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by Nef1k** [comment]
Ну, радует, что он стал нормально парсить

**Comment by Zzzkvidi4** [comment]
Ахах)

**Comment by Nef1k** [comment]
Хрен знает, почему оно так

**Comment by Nef1k** [comment]
У тебя оно до сих пор не запускается7

**Comment by Zzzkvidi4** [comment]
D:\Work\Chat\CommandSystem\src\com\ns_team\commands_system\param\ParamList.java
Error:(11, 22) java: generics are not supported in -source 1.3
  (use -source 5 or higher to enable generics)
Error:(14, 35) java: diamond operator is not supported in -source 1.3
  (use -source 7 or higher to enable diamond operator)
D:\Work\Chat\CommandSystem\src\com\ns_team\commands_system\CommandManager.java
Error:(16, 22) java: generics are not supported in -source 1.3
  (use -source 5 or higher to enable generics)
Error:(19, 33) java: diamond operator is not supported in -source 1.3
  (use -source 7 or higher to enable diamond operator)

**Comment by Nef1k** [comment]
Косяк в том, что CommandManager.getCommandById возвращает null. 
Косячно вот что:
1. Не установлена команда по-умолчанию (сейчас поправлю)
2. Тем не менее, это не тот случай, когда она должна отрабатывать. Тут указана зарегистрированная команда...

**Comment by Nef1k** [comment]
Теперь оно культурно выдаёт Invalid command. 
Значит, косяк в getCommandById

**Comment by Nef1k** [comment]
Выяснилось, что в getCommandById поступает неверный ID, в связи с чем пока ставлю на паузу этот issue

**Comment by Nef1k** [comment]
Fixed
