### ISSUE TITLE
Косяк при парсинге ID команды

### ISSUE THREAD

**Issue by Nef1k** [Nef1k/CommandSystem#5]
Вместо test_cmd оно парсит est_cmd. То бишь, обрубает первый символ.

**Comment by Zzzkvidi4** [comment]
Сейчас займусь... Нелегко дебажить, если оно не запускается)))

**Comment by Zzzkvidi4** [comment]
Выяснилось, что метод изъятия подстроки работает слегка иначе, чем я себе представлял

**Comment by Zzzkvidi4** [comment]
Версия обновлена.

**Comment by Nef1k** [comment]
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1967)
	at com.ns_team.commands_system.Parser.parseCommand(Parser.java:22)
	at com.ns_team.commands_system.CommandManager.executeCommandString(CommandManager.java:29)
	at com.ns_team.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by Zzzkvidi4** [comment]
Добавлена новая версия.

**Comment by Nef1k** [comment]
Всё ещё Invalid command. Сейчас буду разбираться, почему

**Comment by Zzzkvidi4** [comment]
А какой Id теперь?

**Comment by Nef1k** [comment]
Кек
